### ISSUE TITLE
Smooth Lighting Breaks Biome Sight Buff

### ISSUE THREAD

**Issue by Ethan-Hall-1080** [RandomComputerUser/FancyLighting-Terraria#3]
The biome sight buff highlights blocks in a similar way to the spelunker buff. However, enabling the smooth lighting option in this mod will disable this effect for the biome sight buff. (Note: The spelunker buff still works fine.) 
![SmoothLightingComparison](https://github.com/RandomComputerUser/FancyLighting-Terraria/assets/93738475/e4f99249-073d-43c5-a5af-2e30239c049e)

**Comment by RexBerry** [comment]
This has been fixed in v0.7.1.4.
